### ISSUE TITLE
Anomalija na prvih dveh straneh

### ISSUE THREAD

**Issue by GCerar** [strelec/Diplomsko-delo-LaTeX-predloga#1]
Anomalija se mi pojavlja v Linux-u, terminal, ukaz `pdflatex -shell-escape delo.tex`. Izgleda kot nekakšen ostanek LaTeX kode. (texlive 2015/dev)

[primer](https://github.com/strelec/Diplomsko-delo-LaTeX-predloga/files/56110/delo.pdf)

**Comment by strelec** [comment]
Hmm. To se ne bi smelo dogajati. Kakšen output ti da tvoj zgornji ukaz? Mimgrede, prilepi še `emerge --info`.

**Comment by GCerar** [comment]
Če grem interactive mode je na koncu loga napisan kje se ustavi.
[pdflatex -shell-escape delo.tex > log.txt](https://github.com/strelec/Diplomsko-delo-LaTeX-predloga/files/56757/log.txt)

Še complete log z noninteractive.
[pdflatex -interaction=nonstopmode -shell-escape delo.tex > log2.txt](https://github.com/strelec/Diplomsko-delo-LaTeX-predloga/files/56760/log2.txt)

Sem na NixOS. Kaj specifično te zanima od Gentoo-jevga emerge info?

**Comment by GCerar** [comment]
Težava je upstream v distribuciji linuxa, se opravičujem.

**Comment by strelec** [comment]
Ok, ni problema. Pričakuj ene par popravkov ta vikend.

Kar se pa Gentooja tiče, pa vedno raje vprašam, ker zna kak USE flag povzročit določenega hrošča.
